#include "LocalString.hpp"
#include <unordered_map>

Language currentLanguage = ENGLISH;

const std::unordered_map<LocalString, std::string> englishStrings = {
    { INSERT_CARD, "Insert Card" },
    { WITHDRAWAL_MSG, "Withdrawal" },
    { ENTER_PIN, "Enter Pin" },
    { CANCEL, "Cancel" },
    { CLEAR, "Clear" },
    { ENTER, "Enter" },
    { ENTER, "Enter" },
    { BALANCE_INQUIRY, "Balance Inquiry" },
    { DEPOSIT_MSG, "Deposit" },
    { EXIT, "Exit" },
    { L_ENGLISH, "English" },
    { L_FRENCH, "French" },
    { L_SPANISH, "Spanish" },
    { L_GERMAN, "German" },
    {SELECT_LANG, "Select Language"},
    {SELECT_OPTION, "Select an option below"},
    {VIEW_BALANCE, "View Balance"},
    {PRINT_BALANCE, "Print balance"},
    {YOUR_BALANCE, "Balance:"},
    {BACK, "Go back"},
    {PROCESSING, "Processing..."},
    {TAKE_RECEIPT, "Please take your receipt"},
    {CUSTOM_AMOUNT, "Custom Amount"},
    {TRANSACTION_SUCCESS, "Transaction Successful"},
    {WITHDRAWAL_AMOUNT, "Enter withdrawal amount"},
    {DEPOSIT_AMOUNT, "Enter deposit amount"},
    {GENERIC_ERROR_MSG, "Network Error"},
    {INSUFFICIENT_FUNDS_MSG, "Insufficient Funds"},
    {INCORRECT_PIN_MSG, "Incorrect PIN"},
    {CASH, "Cash"},
};

const std::unordered_map<LocalString, std::string> frenchStrings = {
    { INSERT_CARD, "Insérez la carte" },
    { WITHDRAWAL_MSG, "Retrait" },
    { ENTER_PIN, "Entrez le code PIN" },
    { CANCEL, "Annuler" },
    { CLEAR, "Effacer" },
    { ENTER, "Entrer" },
    { BALANCE_INQUIRY, "Consultation de solde" },
    { DEPOSIT_MSG, "Dépôt" },
    { EXIT, "Quitter" },
    { L_ENGLISH, "Anglais" },
    { L_FRENCH, "Français" },
    { L_SPANISH, "Espagnol" },
    { L_GERMAN, "Allemand" },
    { SELECT_LANG, "Sélectionnez la langue" },
    { SELECT_OPTION, "Sélectionnez une option ci-dessous" },
    { VIEW_BALANCE, "Voir le solde" },
    { PRINT_BALANCE, "Imprimer le solde" },
    { YOUR_BALANCE, "Solde :" },
    { BACK, "Retour" },
    { PROCESSING, "Traitement en cours..." },
    { TAKE_RECEIPT, "Veuillez prendre votre reçu" },
    { CUSTOM_AMOUNT, "Montant personnalisé" },
    { TRANSACTION_SUCCESS, "Transaction réussie" },
    { WITHDRAWAL_AMOUNT, "Entrez le montant du retrait" },
    { DEPOSIT_AMOUNT, "Entrez le montant du dépôt" },
    { GENERIC_ERROR_MSG, "Erreur réseau" },
    { INSUFFICIENT_FUNDS_MSG, "Fonds insuffisants" },
    { INCORRECT_PIN_MSG, "Code PIN incorrect" },
    { CASH, "Espèces" },
};

const std::unordered_map<LocalString, std::string> spanishStrings = {
    { INSERT_CARD, "Inserte la tarjeta" },
    { WITHDRAWAL_MSG, "Retiro" },
    { ENTER_PIN, "Ingrese el PIN" },
    { CANCEL, "Cancelar" },
    { CLEAR, "Borrar" },
    { ENTER, "Ingresar" },
    { BALANCE_INQUIRY, "Consulta de saldo" },
    { DEPOSIT_MSG, "Depósito" },
    { EXIT, "Salir" },
    { L_ENGLISH, "Inglés" },
    { L_FRENCH, "Francés" },
    { L_SPANISH, "Español" },
    { L_GERMAN, "Alemán" },
    { SELECT_LANG, "Seleccione el idioma" },
    { SELECT_OPTION, "Seleccione una opción abajo" },
    { VIEW_BALANCE, "Ver saldo" },
    { PRINT_BALANCE, "Imprimir saldo" },
    { YOUR_BALANCE, "Saldo:" },
    { BACK, "Regresar" },
    { PROCESSING, "Procesando..." },
    { TAKE_RECEIPT, "Por favor tome su recibo" },
    { CUSTOM_AMOUNT, "Monto personalizado" },
    { TRANSACTION_SUCCESS, "Transacción exitosa" },
    { WITHDRAWAL_AMOUNT, "Ingrese el monto del retiro" },
    { DEPOSIT_AMOUNT, "Ingrese el monto del depósito" },
    { GENERIC_ERROR_MSG, "Error de red" },
    { INSUFFICIENT_FUNDS_MSG, "Fondos insuficientes" },
    { INCORRECT_PIN_MSG, "PIN incorrecto" },
    { CASH, "Efectivo" },
};

const std::unordered_map<LocalString, std::string> germanStrings = {
    { INSERT_CARD, "Karte einführen" },
    { WITHDRAWAL_MSG, "Abhebung" },
    { ENTER_PIN, "PIN eingeben" },
    { CANCEL, "Abbrechen" },
    { CLEAR, "Löschen" },
    { ENTER, "Eingeben" },
    { BALANCE_INQUIRY, "Kontostand abfragen" },
    { DEPOSIT_MSG, "Einzahlung" },
    { EXIT, "Beenden" },
    { L_ENGLISH, "Englisch" },
    { L_FRENCH, "Französisch" },
    { L_SPANISH, "Spanisch" },
    { L_GERMAN, "Deutsch" },
    { SELECT_LANG, "Sprache wählen" },
    { SELECT_OPTION, "Wählen Sie eine Option unten" },
    { VIEW_BALANCE, "Kontostand anzeigen" },
    { PRINT_BALANCE, "Kontostand drucken" },
    { YOUR_BALANCE, "Kontostand:" },
    { BACK, "Zurück" },
    { PROCESSING, "Verarbeitung..." },
    { TAKE_RECEIPT, "Bitte nehmen Sie Ihre Quittung" },
    { CUSTOM_AMOUNT, "Benutzerdefinierter Betrag" },
    { TRANSACTION_SUCCESS, "Transaktion erfolgreich" },
    { WITHDRAWAL_AMOUNT, "Betrag für Abhebung eingeben" },
    { DEPOSIT_AMOUNT, "Betrag für Einzahlung eingeben" },
    { GENERIC_ERROR_MSG, "Netzwerkfehler" },
    { INSUFFICIENT_FUNDS_MSG, "Unzureichende Mittel" },
    { INCORRECT_PIN_MSG, "Falsche PIN" },
    { CASH, "Bargeld" },
};

const std::unordered_map<Language, std::unordered_map<LocalString, std::string>> languageStrings = {
    { ENGLISH, englishStrings },
    { FRENCH, frenchStrings },
    { SPANISH, spanishStrings },
    { GERMAN, germanStrings }
};



std::string inCurrentLanguage(LocalString str) {
    return languageStrings.at(currentLanguage).at(str);
}